@snoopy_airlines_backend_HostAddress = http://localhost:5235

GET {{snoopy_airlines_backend_HostAddress}}/Flight
Accept: application/json

###

POST {{snoopy_airlines_backend_HostAddress}}/Flight
Content-Type: application/json

{
  "id": 0,
  "airplaneId": 1,
  "departureAirportId": 1,
  "arrivalAirportId": 2,
  "departureTime": "2026-04-19T08:00:00",
  "arrivalTime": "2026-04-19T10:30:00",
  "durationMinutes": 150,
  "priceFirstClass": 350.00,
  "priceEconomyClass": 120.00,
  "priceCarryOnBaggage": 25.00,
  "priceCheckedBaggage": 40.00,
  "weightLimitCarryOnBaggage": 10,
  "weightLimitCheckedBaggage": 23,
  "checkedBaggagePriceMultiplier": 1.2500
}

###
